keys:
  - &admin age15vwchrrgw9gyn5fvc54zsg7vyktqdcer88vp8rpgn3zj5l796yms447awl
  - &nixos-laptop age1f600f3g7d2jdfazjj90xzqzzaus29j2ejqsyzxw6uk5hv60s53qqq55lma
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
        - *admin
        - *nixos-laptop
